services:
  frontend:
    command: sh -c "npm install && npx next dev -H 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FLASK_BASE_URL=http://nginx
      - NEXT_TELEMETRY_DISABLED=1
